name: costarica_app
description: costarica app project

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  provider: ^6.0.4
  go_router: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/glogo.png
    - assets/images/kakaologo.png
    - assets/images/email.png
    - assets/icons/close.png
    - assets/icons/arrow_back.png
    - assets/icons/close_circle.png

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
  
